function getSoB() {

var grenades = {
					id:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2"
					},
					available:false,
					label:"Grenades",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						name:"Frag Grenades",
						display:'checkbox',
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						name:"Krak Grenades",
						display:'checkbox',
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					}]
				};

var immolator = {
				id:"12",
				name:"Immolator",
				enable:false,
				type:"machine",
				cost:"60",
				count:"1",
				minCount:"1",
				maxCount:"1",
				BS:"4",
				FA:"11",
				SA:"11",
				BA:"10",
				HP:"3",
				specialRules: [
					{name:"Shield Of Faith"}
				],
				upgrades: [{
					id:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapons",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Smoke Launchers",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"2",
						quantity:"1",
						available:true,
						display:'checkbox',
						name:"Twin-linked Heavy Flamer",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Twin-linked Heavy Bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Twin-linked Multi-melta",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"2",
					counterManager:{
						type:"static",
						maxCount:"8",
						minCount:"0",
					},
					available:true,
					label:"Wargear",
					type:"static",
					stuff:[{
						id:"6",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Searchlight",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Dozer Blade",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Hunter-killer Missile",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Laud Hailer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"5",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Extra Armour",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
		    }
			
var rhino = {
				id:"11",
				name:"Rhino",
				enable:false,
				type:"machine",
				cost:"40",
				count:"1",
				minCount:"1",
				maxCount:"1",
				BS:"4",
				FA:"11",
				SA:"11",
				BA:"10",
				HP:"3",
				specialRules: [
					{name:"Repair"},
					{name:"Shield Of Faith"}
				],
				upgrades: [{
					id:"1",
					counterManager:{
						type:"static",
						maxCount:"3",
						minCount:"3",
					},
					available:false,
					type:"static",
					label:"Weapons",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Storm bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Smoke Launchers",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Searchlight",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					}]
				},{
					id:"2",
					counterManager:{
						type:"static",
						maxCount:"8",
						minCount:"0",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Dozer Blade",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Hunter-killer Missile",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Laud Hailer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"5",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Extra Armour",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
		    }

var veterans = {
				id:"12",
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				available:true,
				label:"Veteran",
				type:"static",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					display:'checkbox',
					name:"Veteran",
					cost:"10",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
}

	return {armyName:"Sisters Of Battle",
			 armyCode:"SoB",
			 alliancesList:[{
				armyCode:'BA',
				relationCode:'Bro',
				relationName:'Battle Brothers'
			 },{
				armyCode:"CSM",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"DA",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"DE",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"Dem",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"Eld",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"GK",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"IG",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"Nec",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"Orc",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"SM",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"SoB",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"SW",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"Tau",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"Tyr",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			},{
				armyCode:"Inq",
				relationCode:'Bro',
				relationName:'Battle Brothers'
			}],
			countConditions:{
				hq:{
					min:"1",
					max:"2",
					minError:"you need at least one HQ unit",
					maxError:"you can't have more then two HQ units"
				},
				troops: {
					min:"2",
					max:"6",
					minError:"you have to take at least two troops choise",
					maxError:"you can't have more then six troops units"
				},
				fast: {
					min:"0",
					max:"3",
					minError:"same system Error",
					maxError:"you can't have more then three fast units"
				},
				elite: {
					min:"0",
					max:"3",
					minError:"same system Error",
					maxError:"you can't have more then three elite units"
				},
				heavy: {
					min:"0",
					max:"3",
					minError:"same system Error",
					maxError:"you can't have more then three heavy units"
				},
				fort: {
					min:"0",
					max:"3",
					minError:"same system Error",
					maxError:"you can't have more then three heavy units"
				}
			},	
			 units:[{
			id:"1", /*Saint Celestine*/
			role:"hq",
			armyCode:"SoB",
			name:"Saint Celestine",
			icon:'images/Icons/SistersOfBattle/HQ/SaintCelestine.jpg',
			upgrades:[],
			models:[{
				id:"1",
				name:"Saint Celestine",
				enable:true,
				type:"infantry",
				modelType:"JmpInf",
				cost:"135",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"7",
				BS:"7",
				S:"3",
				T:"3",
				W:"3",
				In:"7",
				At:"5",
				Ld:"10",
				save:"2",
				specialRules: [
					{name:"Independent Character"},
					{name:"Act Of Faith"},
					{name:"Fearless"},
					{name:"Hit & Run"},
					{name:"Martyrdom"},
					{name:"Shield Of Faith"},
					{name:"Beacon Of Faith"}
				],
				upgrades: [grenades,
				{
					id:"2", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"3",
						minCount:"3",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Jump Pack",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"The Ardent Blade",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"3",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Armour Of Saint Katherine",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					}]
				}]	
			}]
		},{
			id:"2", /*Uriah Jacobus*/
			role:"hq",
			armyCode:"SoB",
			name:"Uriah Jacobus",
			icon:'images/Icons/SistersOfBattle/HQ/UriahJacobus.jpg',
			upgrades:[],
			models:[{
				id:"1",
				name:"Uriah Jacobus",
				enable:true,
				type:"infantry",
				cost:"100",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"4",
				BS:"4",
				S:"3",
				T:"3",
				W:"3",
				In:"4",
				At:"3",
				Ld:"9",
				save:"5",
				invSave:"4",
				specialRules: [
					{name:"Independent Character"},
					{name:"Martyrdom"},
					{name:"Shield Of Faith"},
					{name:"Protector Of Faith"},
					{name:"War Hymns"},
					{name:"Zealot"},
					{name:"Indomitable Belief"}
				],
				upgrades: [grenades,
				{
					id:"2", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"6",
						minCount:"6",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Flak Armour",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"3",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"4",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Rosarius",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"5",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"The Redeemer",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"6",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"The Banner Of Sanctity",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					}]
				}]	
			}]
		},{
			id:"3", /*Canoness*/
			role:"hq",
			armyCode:"SoB",
			name:"Canoness",
			icon:'images/Icons/SistersOfBattle/HQ/canoness.jpg',
			upgrades:[],
			models:[{
				id:"1",
				name:"Canoness",
				enable:true,
				type:"infantry",
				cost:"65",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"5",
				BS:"5",
				S:"3",
				T:"3",
				W:"3",
				In:"4",
				At:"3",
				Ld:"10",
				save:"3",
				specialRules: [
					{name:"Independent Character"},
					{name:"Martyrdom"},
					{name:"Shield Of Faith"},
					{name:"Act Of Faith"},
					{name:"Stubborn"}
				],
				upgrades: [grenades,
				{
					id:"2", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"1",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Rosarius",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					}]
				},{
					id:"3", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Power Weapon",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Eviscerator",
						cost:"30",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"4",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"5",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"7",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"8",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-flamer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"9",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-melta",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"10",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-plasma",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"11",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Condemnor Boltgun",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"12",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"13",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Inferno Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					}]
				},{
					id:"4", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					type:"static",
					label:"Relics",
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Book Of St.Lucius",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Litanies Of Faith",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Cloak Of St. Aspira",
						cost:"20",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"4",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Mantle Of Ophelia",
						cost:"25",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"5",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Blade Of Admonition",
						cost:"30",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					}]
				}]	
			}]
		},{
			id:"4", /*Battle Conclave*/
			role:"hq",
			armyCode:"SoB",
			name:"Battle Conclave",
			icon:'images/Icons/SistersOfBattle/HQ/BattleConclave.jpg',
			upgrades:[{
				id:"1",
				label:"Warband",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"10",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Arco-flagellant",
					display:'checkbox',
					modelId:"1",
					cost:"15",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"3",
					quantity:"0",
					available:true,
					name:"Crusader",
					display:'checkbox',
					modelId:"3",
					cost:"15",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"5",
					quantity:"0",
					available:true,
					name:"Death Cult Assassin",
					display:'checkbox',
					modelId:"5",
					cost:"15",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			},{
				id:"4",
				maxquantity:"1",
				label:"dedicate transport",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Rhino",
					modelId:"11",
					cost:"40",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Immolator",
					modelId:"12",
					cost:"60",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			models:[{
				id:"1",
				name:"Arco-flagellant",
				enable:false,
				type:"infantry",
				cost:"10",
				count:"0",
				minCount:"0",
				maxCount:"10",
				WS:"5",
				BS:"1",
				S:"5",
				T:"3",
				W:"1",
				In:"3",
				At:"3",
				Ld:"8",
				save:"-",
				specialRules: [
					{name:"Feel No Pain"}
				],
				upgrades: [{
					id:"2", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"2",
						display:'checkbox',
						available:false,
						name:"Arco-flails",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"2",
							minCount:"2",
						}
					}]
				}]	
			},{
				id:"3",
				name:"Crusader",
				enable:false,
				type:"infantry",
				cost:"15",
				count:"0",
				minCount:"0",
				maxCount:"10",
				WS:"4",
				BS:"3",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"5",
				invSave:"3",
				specialRules: [],
				upgrades: [{
					id:"2", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"3",
						minCount:"3",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Flak Armour",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Power Weapon",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"3",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Storm Shield",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]	
			},{
				id:"5",
				name:"Death Cult Assassin",
				enable:false,
				type:"infantry",
				cost:"15",
				count:"0",
				minCount:"0",
				maxCount:"12",
				WS:"5",
				BS:"3",
				S:"4",
				T:"3",
				W:"1",
				In:"6",
				At:"2",
				Ld:"8",
				save:"5",
				invSave:"5",
				specialRules: [
					{name:"Ancanny Reflecxes"}
				],
				upgrades: [{
					id:"2", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"3",
						minCount:"3",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Flak Armour",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"1",
						quantity:"2",
						display:'checkbox',
						available:false,
						name:"Power Weapon",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"2",
							minCount:"2",
						}
					}]
				}]	
			}
			,rhino
			,immolator]
		},{
			id:"5", /*Ministorum Priest*/
			role:"hq",
			armyCode:"SoB",
			name:"Ministorum Priest",
			icon:'images/Icons/SistersOfBattle/HQ/ministorumpriest.jpg',
			upgrades:[],
			models:[{
				id:"1",
				name:"Ministorum Priest",
				enable:true,
				type:"infantry",
				cost:"25",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"3",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"7",
				save:"5",
				specialRules: [
					{name:"Independent Character"},
					{name:"War Hymns"},
					{name:"Zealot"}
				],
				upgrades: [grenades,
				{
					id:"2", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Flak Armour",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Rosarius",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					}]
				},{
					id:"3", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Power Weapon",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Eviscerator",
						cost:"30",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"4",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Laspistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"5",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Autogun",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"6",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Bolt PIstol",
						cost:"1",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"7",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Boltgun",
						cost:"1",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"8",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Plasma Gun",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"9",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Melta Bomb",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"10",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Shotgun",
						cost:"1",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"11",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-flamer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"12",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-melta",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"13",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-plasma",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"14",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Condemnor Boltgun",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"15",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					}]
				},{
					id:"4", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					type:"static",
					label:"Relics",
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Book Of St.Lucius",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Litanies Of Faith",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Cloak Of St. Aspira",
						cost:"20",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"4",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Mantle Of Ophelia",
						cost:"25",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"6",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Mace Of Valaan",
						cost:"25",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					}]
				}]	
			}]
		},{id:"6", /*Command Squad*/
			 role:"hq",
			 armyCode:"SoB",
			 name:"Command Squad",
			 icon:'images/Icons/SistersOfBattle/HQ/commandsquad.jpg',
			 upgrades:[{
				id:"5",
				label:"Champions",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"2",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Hospitaller",
					display:'checkbox',
					modelId:"2",
					cost:"10",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Dialogus",
					display:'checkbox',
					modelId:"3",
					cost:"5",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			},{
				id:"4",
				maxquantity:"1",
				label:"Dedicate Transport",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Rhino",
					modelId:"11",
					cost:"40",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Immolator",
					modelId:"12",
					cost:"60",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			 models:[
			 {
				id:"1",
				name:"Celestian",
				enable:true,
				type:"infantry",
				cost:"13",
				count:"5",
				minCount:"5",
				maxCount:"5",
				WS:"4",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"9",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"},
					{name:"Stubborn"}
				],
				upgrades: [grenades,
				{
					id:"2",
					counterManager:{
						type:"dependOnModelCount",
						modelId:"1",
						countSet:[{
							modelCount:"3",
							minCount:"6",
							maxCount:"6"
						},{
							modelCount:"4",
							minCount:"8",
							maxCount:"8"
						},{
							modelCount:"5",
							minCount:"10",
							maxCount:"10"
						}],
					},
					available:true,
					label:"Weapons",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"5",
						available:true,
						display:'multi',
						name:"Bolter",
						cost:"0",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"2",
						quantity:"5",
						available:true,
						display:'multi',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"4",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Power Weapon",
						cost:"15",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"6"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"8"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"10"
							}],
						}
					},{
						id:"5",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"6",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Combi-Flamer",
						cost:"10",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"7",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Combi-Melta",
						cost:"10",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"8",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Combi-Plasma",
						cost:"10",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"9",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"10",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Condemnor Bolter",
						cost:"10",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"11",
						available:true,
						quantity:"0",
						name:"Flamer",
						display:'multi',
						cost:"5",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"12",
						available:true,
						quantity:"0",
						name:"Meltagun",
						display:'multi',
						cost:"5",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"13",
						available:true,
						quantity:"0",
						name:"Heavy Bolter",
						display:'multi',
						cost:"10",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"14",
						available:true,
						quantity:"0",
						name:"Heavy Flamer",
						display:'multi',
						cost:"15",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					},{
						id:"15",
						available:true,
						quantity:"0",
						name:"Multi-melta",
						display:'multi',
						cost:"10",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					}]
				},{
					id:"3", /*Melta bomb*/
					available:true,
					type:"static",
					label:"Melta Bomb",
					counterManager:{
						type:"dependOnModelCount",
						modelId:"1,2,3",
						countSet:[{
							modelCount:"3",
							minCount:"0",
							maxCount:"3"
						},{
							modelCount:"4",
							minCount:"0",
							maxCount:"4"
						},{
							modelCount:"5",
							minCount:"0",
							maxCount:"5"
						}],
					},
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Melta Bomb",
						cost:"5",
						counterManager:{
							type:"dependOnModelCount",
							modelId:"1",
							countSet:[{
								modelCount:"3",
								minCount:"0",
								maxCount:"3"
							},{
								modelCount:"4",
								minCount:"0",
								maxCount:"4"
							},{
								modelCount:"5",
								minCount:"0",
								maxCount:"5"
							}],
						}
					}]
				},{
					id:"5", /*Company Standart*/
					available:true,
					type:"static",
					label:"Banner",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Blessed Standard",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Sacred Banner Of The Order Militant",
						cost:"40",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"6", /*Company Standart*/
					available:true,
					type:"static",
					label:"Wargear",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Simulacrum Imperialis",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
			},{
				id:"2",
				role:"troops",
				name:"Hospitaller",
				enable:false,
				type:"infantry",
				cost:"23",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"9",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"},
					{name:"Stubborn"}
				],
				upgrades: [grenades,
				{
					id:"2",
					available:false,
					type:"static",
					label:"Wargear",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					stuff:[{
						id:"4",
						quantity:"1",
						available:false,
						name:"Bolt Pistol",
						display:'checkbox',
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					},{
						id:"5",
						quantity:"1",
						available:false,
						name:"Chirurgeon's Tools",
						display:'checkbox',
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					}]
				},{
					id:"3",
					available:true,
					type:"modelCounter",
					modelId:"1",
					display:'hidden',
					counterManager:{
						modelId:"3",
						type:"dependOnModelCount",
						countSet:[{
							modelCount:"0",
							minCount:"0",
							maxCount:"0"
						},{
							modelCount:"1",
							minCount:"1",
							maxCount:"1"
						}],
					},
					operator:"minus",
					value:"1",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						name:"counter",
						display:'hidden',
						cost:"0",
						counterManager:{
							modelId:"3",
							type:"dependOnModelCount",
							countSet:[{
								modelCount:"0",
								minCount:"0",
								maxCount:"0"
							},{
								modelCount:"1",
								minCount:"1",
								maxCount:"1"
							}],
						}
					}]
				}]
			},{
				id:"3",
				name:"Dialogus",
				enable:false,
				type:"infantry",
				cost:"18",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"9",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"},
					{name:"Stubborn"}
				],
				upgrades: [grenades,
				{
					id:"2",
					available:true,
					type:"static",
					label:"Wargear",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					stuff:[{
						id:"2",
						quantity:"1",
						name:"Laud Hailer",
						display:'checkbox',
						cost:"0",
						available:false,
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"1",
						available:false,
						name:"Bolt Pistol",
						display:'checkbox',
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"4", /*wargear*/
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					type:"static",
					label:"Relics",
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Book Of St.Lucius",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Litanies Of Faith",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Cloak Of St. Aspira",
						cost:"20",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"4",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"The Mantle Of Ophelia",
						cost:"25",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					}]
				},{
					id:"3",
					available:true,
					type:"modelCounter",
					modelId:"1",
					display:'hidden',
					counterManager:{
						modelId:"3",
						type:"dependOnModelCount",
						countSet:[{
							modelCount:"0",
							minCount:"0",
							maxCount:"0"
						},{
							modelCount:"1",
							minCount:"1",
							maxCount:"1"
						}],
					},
					operator:"minus",
					value:"1",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						name:"counter",
						display:'hidden',
						cost:"0",
						counterManager:{
							modelId:"3",
							type:"dependOnModelCount",
							countSet:[{
								modelCount:"0",
								minCount:"0",
								maxCount:"0"
							},{
								modelCount:"1",
								minCount:"1",
								maxCount:"1"
							}],
						}
					}]
				}]
			}
			,rhino
			,immolator]
		},{id:"7", /*Battle Sister Squad*/
			 role:"troops",
			 armyCode:"SoB",
			 name:"Battle Sister Squad",
			 icon:'images/Icons/SistersOfBattle/Troops/battlesquad.jpg',
			 upgrades:[{
				id:"4",
				maxquantity:"1",
				label:"Dedicate Transport",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Rhino",
					modelId:"11",
					cost:"40",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Immolator",
					modelId:"12",
					cost:"60",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			 models:[
			 {
				id:"1",
				name:"Battle Sister",
				enable:true,
				type:"infantry",
				cost:"12",
				count:"4",
				minCount:"4",
				maxCount:"19",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,
				{
					id:"2",
					counterManager:{
						type:"static",
						minCount:"3",
						maxCount:"3"
					},
					available:true,
					label:"Wargear",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Boltgun",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						minCount:"0",
						maxCount:"1"
					},
					available:true,
					label:"Special Weapon",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Flamer",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Meltagun",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					}]
				},{
					id:"4",
					counterManager:{
						type:"static",
						minCount:"0",
						maxCount:"1"
					},
					available:true,
					label:"Special Weapon",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Flamer",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Meltagun",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"4",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Heavy Bolter",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"5",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Heavy Flamer",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"6",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Multi-melta",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					}]
				},{
					id:"6", /*Company Standart*/
					available:true,
					type:"static",
					label:"Wargear",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Simulacrum Imperialis",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
			},{
				id:"2",
				role:"troops",
				name:"Sister Superior",
				enable:true,
				type:"infantry",
				cost:"12",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,{
					id:"2", /*pistols, bolters, CC*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolt pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"5",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Melta",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"6",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Flamer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"7",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Plasma",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"8",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"9",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Power Weapon",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"melta bomb",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"melta bomb",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}
				,veterans]
			}
			,rhino
			,immolator]
		},{id:"8", /*Celestian Squad*/
			 role:"elite",
			 armyCode:"SoB",
			 name:"Celestian Squad",
			 icon:'images/Icons/SistersOfBattle/Elite/celestiansquad.jpg',
			 upgrades:[{
				id:"4",
				maxquantity:"1",
				label:"Dedicate Transport",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Rhino",
					modelId:"11",
					cost:"40",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Immolator",
					modelId:"12",
					cost:"60",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			 models:[
			 {
				id:"1",
				name:"Celestian",
				enable:true,
				type:"infantry",
				cost:"14",
				count:"4",
				minCount:"4",
				maxCount:"9",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"9",
				save:"3",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,
				{
					id:"2",
					counterManager:{
						type:"static",
						minCount:"3",
						maxCount:"3"
					},
					available:true,
					label:"Wargear",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Boltgun",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						minCount:"0",
						maxCount:"1"
					},
					available:true,
					label:"Special Weapon",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Flamer",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Meltagun",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					}]
				},{
					id:"4",
					counterManager:{
						type:"static",
						minCount:"0",
						maxCount:"1"
					},
					available:true,
					label:"Special Weapon",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Flamer",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Meltagun",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"4",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Heavy Bolter",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"5",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Heavy Flamer",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					},{
						id:"6",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Multi-melta",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"1"
						}
					}]
				},{
					id:"6", /*Company Standart*/
					available:true,
					type:"static",
					label:"Wargear",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Simulacrum Imperialis",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
			},{
				id:"2",
				role:"troops",
				name:"Celestian Superior",
				enable:true,
				type:"infantry",
				cost:"14",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"9",
				save:"3",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,{
					id:"2", /*pistols, bolters, CC*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolt pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"5",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Melta",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"6",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Flamer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"7",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Plasma",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"8",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"9",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Power Weapon",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"melta bomb",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"melta bomb",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
			}
			,rhino
			,immolator]
		},{id:"9", /*Repentia Squad*/
			 role:"elite",
			 armyCode:"SoB",
			 name:"Repentia Squad",
			 icon:'images/Icons/SistersOfBattle/Elite/repentiasquad.jpg',
			 upgrades:[{
				id:"4",
				maxquantity:"1",
				label:"Dedicate Transport",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Rhino",
					modelId:"11",
					cost:"40",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Immolator",
					modelId:"12",
					cost:"60",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			 models:[
			 {
				id:"1",
				name:"Sister Repentia",
				enable:true,
				type:"infantry",
				cost:"14",
				count:"4",
				minCount:"4",
				maxCount:"9",
				WS:"4",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Fearless"},
					{name:"Fleet"},
					{name:"Rage"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,
				{
					id:"2",
					counterManager:{
						type:"static",
						minCount:"2",
						maxCount:"2"
					},
					available:true,
					label:"Wargear",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Eviscerator",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					}]
				}]
			},{
				id:"2",
				name:"Sister Of Repentance",
				enable:true,
				type:"infantry",
				cost:"29",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"9",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Fearless"},
					{name:"Fleet"},
					{name:"Rage"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,{
					id:"2", /*pistols, bolters, CC*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"3",
						minCount:"3",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"2",
						available:false,
						display:'checkbox',
						name:"Neural Whip",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"2",
							maxCount:"2"
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"melta bomb",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"melta bomb",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
			}
			,rhino
			,immolator]
		},{id:"10", /*Seraphim Squad*/
			 role:"fast",
			 armyCode:"SoB",
			 name:"Seraphim Squad",
			 icon:'images/Icons/SistersOfBattle/Fast/seraphimsquad.jpg',
			 upgrades:[{
				id:"5",
				label:"Seraphim Superior",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"2",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Seraphim Superior",
					display:'checkbox',
					modelId:"2",
					cost:"10",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			 models:[
			 {
				id:"1",
				name:"Seraphim",
				enable:true,
				type:"infantry",
				modelType:"JmpInf",
				cost:"15",
				count:"5",
				minCount:"5",
				maxCount:"10",
				WS:"4",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Hit & Run"},
					{name:"Angelic Visage"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,
				{
					id:"2",
					counterManager:{
						type:"static",
						minCount:"4",
						maxCount:"4"
					},
					available:true,
					label:"Wargear",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Jump Pack",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"2",
						available:false,
						display:'checkbox',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"2",
							maxCount:"2"
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						minCount:"0",
						maxCount:"2"
					},
					available:true,
					label:"Special Weapon",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Two Hand Flamers",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"2"
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Two Inferno Pistols",
						cost:"30",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"2"
						}
					}]
				}]
			},{
				id:"2",
				name:"Seraphim Superior",
				enable:false,
				type:"infantry",
				modelType:"JmpInf(Ch)",
				cost:"25",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"4",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"2",
				Ld:"9",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Hit & Run"},
					{name:"Angelic Visage"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,{
					id:"2", /*pistols, bolters, CC*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Jump Pack",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"1",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						available:true,
						display:'checkbox',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Power Sword",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"4",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"1",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						available:true,
						display:'checkbox',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"5",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"melta bomb",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"melta bomb",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"6",
					available:true,
					type:"modelCounter",
					modelId:"1",
					display:'hidden',
					counterManager:{
						modelId:"1",
						type:"dependOnModelCount",
						countSet:[{
							modelCount:"0",
							minCount:"0",
							maxCount:"0"
						},{
							modelCount:"1",
							minCount:"1",
							maxCount:"1"
						}],
					},
					operator:"minus",
					value:"1",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						name:"counter",
						display:'hidden',
						cost:"0",
						counterManager:{
							modelId:"3",
							type:"dependOnModelCount",
							countSet:[{
								modelCount:"0",
								minCount:"0",
								maxCount:"0"
							},{
								modelCount:"1",
								minCount:"1",
								maxCount:"1"
							}],
						}
					}]
				}]
			}]
		},{id:"11", /*Dominion Squad*/
			 role:"fast",
			 armyCode:"SoB",
			 name:"Dominion Squad",
			 icon:'images/Icons/SistersOfBattle/Fast/dominionsquad.jpg',
			 upgrades:[{
				id:"4",
				maxquantity:"1",
				label:"Dedicate Transport",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Rhino",
					modelId:"11",
					cost:"40",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Immolator",
					modelId:"12",
					cost:"60",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			 models:[
			 {
				id:"1",
				name:"Dominion Sister",
				enable:true,
				type:"infantry",
				cost:"13",
				count:"4",
				minCount:"4",
				maxCount:"9",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"},
					{name:"Scout"}
				],
				upgrades: [grenades,
				{
					id:"2",
					counterManager:{
						type:"static",
						minCount:"3",
						maxCount:"3"
					},
					available:true,
					label:"Wargear",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Boltgun",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						minCount:"0",
						maxCount:"4"
					},
					available:true,
					label:"Special Weapon",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"4"
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Flamer",
						cost:"5",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"4"
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Meltagun",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"4"
						}
					}]
				},{
					id:"6", /*Company Standart*/
					available:true,
					type:"static",
					label:"Wargear",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Simulacrum Imperialis",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
			},{
				id:"2",
				role:"troops",
				name:"Dominion Superior",
				enable:true,
				type:"infantry",
				cost:"13",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"},
					{name:"Scout"}
				],
				upgrades: [grenades,{
					id:"2", /*pistols, bolters, CC*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolt pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"5",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Melta",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"6",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Flamer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"7",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Plasma",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"8",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"9",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Power Weapon",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"melta bomb",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"melta bomb",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}
				,veterans]
			}
			,rhino
			,immolator]
		},{id:"12", /*Retributor Squad*/
			 role:"heavy",
			 armyCode:"SoB",
			 name:"Retributor Squad",
			 icon:'images/Icons/SistersOfBattle/Heavy/retributorsquad.jpg',
			 upgrades:[{
				id:"4",
				maxquantity:"1",
				label:"Dedicate Transport",
				available:true,
				counterManager:{
					type:"static",
					maxCount:"1",
					minCount:"0",
				},
				checked:false,
				type:"model",
				stuff:[{
					id:"1",
					quantity:"0",
					available:true,
					name:"Rhino",
					modelId:"11",
					cost:"40",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				},{
					id:"2",
					quantity:"0",
					available:true,
					name:"Immolator",
					modelId:"12",
					cost:"60",
					display:'checkbox',
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					}
				}]
			}],
			 models:[
			 {
				id:"1",
				name:"Battle Sister",
				enable:true,
				type:"infantry",
				cost:"12",
				count:"4",
				minCount:"4",
				maxCount:"9",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,
				{
					id:"2",
					counterManager:{
						type:"static",
						minCount:"3",
						maxCount:"3"
					},
					available:true,
					label:"Wargear",
					type:"static",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Power Armour",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Boltgun",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					},{
						id:"3",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Bolt Pistol",
						cost:"0",
						counterManager:{
							type:"static",
							minCount:"1",
							maxCount:"1"
						}
					}]
				},{
					id:"4",
					counterManager:{
						type:"static",
						minCount:"0",
						maxCount:"4"
					},
					available:true,
					label:"Special Weapon",
					type:"static",
					stuff:[{
						id:"4",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Heavy Bolter",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"4"
						}
					},{
						id:"5",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Heavy Flamer",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"4"
						}
					},{
						id:"6",
						quantity:"0",
						available:true,
						display:'multi',
						name:"Multi-melta",
						cost:"10",
						counterManager:{
							type:"static",
							minCount:"0",
							maxCount:"4"
						}
					}]
				},{
					id:"6", /*Company Standart*/
					available:true,
					type:"static",
					label:"Wargear",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Simulacrum Imperialis",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
			},{
				id:"2",
				role:"troops",
				name:"Retributor Superior",
				enable:true,
				type:"infantry",
				cost:"12",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"3",
				BS:"4",
				S:"3",
				T:"3",
				W:"1",
				In:"3",
				At:"1",
				Ld:"8",
				save:"3",
				invSave:"6",
				specialRules: [
					{name:"Act Of Faith"},
					{name:"Shield Of Faith"}
				],
				upgrades: [grenades,{
					id:"2", /*pistols, bolters, CC*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2",
					},
					available:true,
					type:"static",
					label:"Weapon",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolt pistol",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Plasma Pistol",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"5",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Melta",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"6",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Flamer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"7",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Combi-Plasma",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"8",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Chainsword",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"9",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Power Weapon",
						cost:"15",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				},{
					id:"3",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0",
					},
					available:true,
					display:'checkbox',
					type:"static",
					label:"melta bomb",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"melta bomb",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}
				,veterans]
			}
			,rhino
			,immolator]
		},{
			id:"13", /*Exorcist*/
			role:"heavy",
			armyCode:"SoB",
			name:"Exorcist",
			icon:'images/Icons/SistersOfBattle/Heavy/exorcist.jpg',
			upgrades:[],
			models:[{
				id:"1",
				name:"Exorcist",
				enable:true,
				type:"machine",
				cost:"125",
				count:"1",
				minCount:"1",
				maxCount:"1",
				BS:"4",
				FA:"13",
				SA:"11",
				BA:"10",
				HP:"3",
				specialRules: [
					{name:"Shield Of Faith"}
				],
				upgrades: [{
					id:"1",
					counterManager:{
						type:"static",
						maxCount:"3",
						minCount:"3",
					},
					available:false,
					type:"static",
					label:"Weapons",
					stuff:[{
						id:"1",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Exorcist Missile Launcher",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Smoke Launchers",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"1",
						available:false,
						display:'checkbox',
						name:"Searchlight",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1",
						}
					}]
				},{
					id:"2",
					counterManager:{
						type:"static",
						maxCount:"8",
						minCount:"0",
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Dozer Blade",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"2",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Hunter-killer Missile",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"3",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Storm Bolter",
						cost:"5",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"4",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Laud Hailer",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					},{
						id:"5",
						quantity:"0",
						available:true,
						display:'checkbox',
						name:"Extra Armour",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]
		    }]
		},{
			id:"14", /*exorcist*/
			role:"heavy",
			armyCode:"SoB",
			name:"Penitent Engine",
			icon:'images/Icons/SistersOfBattle/Heavy/penitentengine.jpg',
			upgrades:[],
			models:[{
				id:"1",
				name:"Penitent Engine",
				enable:true,
				type:"machine",
				modelType:"W OT",
				cost:"80",
				count:"1",
				minCount:"1",
				maxCount:"3",
				WS:"4",
				BS:"2",
				S:"5",
				In:"3",
				At:"3",
				FA:"11",
				SA:"11",
				BA:"10",
				HP:"3",
				specialRules: [],
				upgrades: [{
					id:"1",
					counterManager:{
						type:"static",
						maxCount:"4",
						minCount:"4",
					},
					available:true,
					type:"static",
					label:"Weapons",
					stuff:[{
						id:"1",
						quantity:"2",
						available:false,
						display:'checkbox',
						name:"Dreadnought CCW",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"2",
							minCount:"2",
						}
					},{
						id:"2",
						quantity:"2",
						available:false,
						display:'checkbox',
						name:"Heavy Flamer",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"2",
							minCount:"2",
						}
					}]
				}]
		    }]
		},{
			id:"51", /*Aegis Defence Lines*/
			role:"fort",
			armyCode:"BA",
			name:"Aegis Defence Lines",
			icon:'images/Icons/Fortification/AegisDefenceLines.png',
			upgrades:[],
			models:[{
				id:"1",
				name:"Aegis Defence Lines",
				enable:true,
				type:"infantry",
				modelType:"",
				cost:"50",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"",
				BS:"",
				S:"",
				T:"",
				W:"",
				In:"",
				At:"",
				Ld:"",
				save:"",
				invSave:"",
				specialRules: [
				],
				upgrades: [{
					id:"2", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0"
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Icarus Lascannon",
						cost:"35",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Quad-gun",
						cost:"50",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Comms Relay",
						cost:"20",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]	
			}]
		},{
			id:"52", /*Imperial Bastion*/
			role:"fort",
			armyCode:"BA",
			name:"Imperial Bastion",
			icon:'images/Icons/Fortification/ImperialBastion.png',
			upgrades:[],
			models:[{
				id:"1",
				name:"Imperial Bastion",
				enable:true,
				type:"infantry",
				modelType:"",
				cost:"75",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"",
				BS:"",
				S:"",
				T:"",
				W:"",
				In:"",
				At:"",
				Ld:"",
				save:"",
				invSave:"",
				specialRules: [
				],
				upgrades: [{
					id:"1", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"4",
						minCount:"4"
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"4",
						display:'checkbox',
						available:false,
						name:"Heavy Bolter",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"4",
							minCount:"4"
						}
					}]
				},{
					id:"2", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"0"
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Icarus Lascannon",
						cost:"35",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Quad-gun",
						cost:"50",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Comms Relay",
						cost:"20",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]	
			}]
		},{
			id:"53", /*Firestorm Redoubt*/
			role:"fort",
			armyCode:"BA",
			name:"Firestorm Redoubt",
			icon:'images/Icons/Fortification/FirestormRedoubt.png',
			upgrades:[],
			models:[{
				id:"1",
				name:"Firestorm Redoubt",
				enable:true,
				type:"infantry",
				modelType:"",
				cost:"200",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"",
				BS:"",
				S:"",
				T:"",
				W:"",
				In:"",
				At:"",
				Ld:"",
				save:"",
				invSave:"",
				specialRules: [
				],
				upgrades: [{
					id:"1", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"2"
					},
					available:true,
					type:"static",
					label:"Weapons",
					stuff:[{
						id:"1",
						quantity:"2",
						display:'checkbox',
						available:false,
						name:"Quad Icarus Lascannon",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"2",
							minCount:"2"
						}
					}]
				}]	
			}]
		},{
			id:"54", /*Skyshield Landing Pad*/
			role:"fort",
			armyCode:"BA",
			name:"Skyshield Landing Pad",
			icon:'images/Icons/Fortification/SkyshieldLandingPad.png',
			upgrades:[],
			models:[{
				id:"1",
				name:"Skyshield Landing Pad",
				enable:true,
				type:"infantry",
				modelType:"",
				cost:"75",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"",
				BS:"",
				S:"",
				T:"",
				W:"",
				In:"",
				At:"",
				Ld:"",
				save:"",
				invSave:"",
				specialRules: [
				],
				upgrades: []	
			}]
		},{
			id:"55", /*Fortress Of Redemption*/
			role:"fort",
			armyCode:"BA",
			name:"Fortress Of Redemption",
			icon:'images/Icons/Fortification/FortressOfRedemption.png',
			upgrades:[],
			models:[{
				id:"1",
				name:"Fortress Of Redemption",
				enable:true,
				type:"infantry",
				modelType:"",
				cost:"250",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"",
				BS:"",
				S:"",
				T:"",
				W:"",
				In:"",
				At:"",
				Ld:"",
				save:"",
				invSave:"",
				specialRules: [
				],
				upgrades: [{
					id:"1", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"4",
						minCount:"0"
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"0",
						display:'multi',
						available:true,
						name:"Heavy Bolter",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"4",
							minCount:"0"
						}
					}]
				},{
					id:"2", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"2",
						minCount:"1"
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:false,
						name:"Twin linked Icarus Lascannon",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"1"
						}
					},{
						id:"2",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Missile Silo(Flak Only)",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"3",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Missile Silo(Frag&Krak)",
						cost:"30",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0",
						}
					}]
				}]	
			}]
		},{
			id:"56", /*Vengeance Weapon Battery*/
			role:"fort",
			armyCode:"BA",
			name:"Vengeance Weapon Battery",
			icon:'images/Icons/Fortification/VengeanceWeaponBattery.png',
			upgrades:[],
			models:[{
				id:"1",
				name:"Vengeance Weapon Battery",
				enable:true,
				type:"infantry",
				modelType:"",
				cost:"75",
				count:"1",
				minCount:"1",
				maxCount:"1",
				WS:"",
				BS:"",
				S:"",
				T:"",
				W:"",
				In:"",
				At:"",
				Ld:"",
				save:"",
				invSave:"",
				specialRules: [
				],
				upgrades: [{
					id:"2", /*wargear*/
					maxquantity:"1",
					counterManager:{
						type:"static",
						maxCount:"1",
						minCount:"1"
					},
					available:true,
					type:"static",
					label:"Wargear",
					stuff:[{
						id:"1",
						quantity:"1",
						display:'checkbox',
						available:true,
						name:"Punisher Gatling Cannon",
						cost:"0",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					},{
						id:"2",
						quantity:"0",
						display:'checkbox',
						available:true,
						name:"Battle Cannon",
						cost:"10",
						counterManager:{
							type:"static",
							maxCount:"1",
							minCount:"0"
						}
					}]
				}]	
			}]
		}]		
	}
}
